# HanaDB Servers.
clusters:
# If you have Failover Partners please concatenate them here like:
# "<failoverserver1-host>:<failoverserver1-port>;<failoverserver2-host>:<failoverserver2-port>"
  - connectionString: "jdbc:sap://<host>:<port>?communicationtimeout=20000"
# User needs the permissions MONITORING and PUBLIC
    username: ""
    password: ""
# Specify encryptionPassword and encryptionKey if Password Encryption Support is required. If not keep it empty.
    encryptionPassword: ""
    encryptionKey: ""

# prefix used to show up metrics in AppDynamics
metricPathPrefix: "Custom Metrics|HanaDB"
# This will create it in specific Tier. Replace <TIER_ID>
# metricPrefix:  "Server|Component:<TIER_ID>|Custom Metrics|HanaDB Server|"
# number of concurrent tasks
numberOfThreads: 10

# Metrics can be converted from b (bytes), to kb (kilobytes), to gb (gigabytes), to tb (terabytes).
# Use the convertFrom and convertTo properties for this.
queries:
  - statement: "select * from M_DISK_USAGE where USED_SIZE >= 0"
    columns:
     - name: "HOST"
       type: "name"
     - name: "USAGE_TYPE"
       type: "name"
     - name: "USED_SIZE"
       type: "metric"
       convertFrom: ""
       convertTo: ""
  - statement: "select HOST, USED_PHYSICAL_MEMORY, FREE_PHYSICAL_MEMORY from M_HOST_RESOURCE_UTILIZATION"
    columns:
     - name: "HOST"
       type: "name"
     - name: "USED_PHYSICAL_MEMORY"
       type: "metric"
       convertFrom: ""
       convertTo: ""
     - name: "FREE_PHYSICAL_MEMORY"
       type: "metric"
       convertFrom: ""
       convertTo: ""